In [1]:
import numpy as np
import pandas as pd 

1.Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. (Score:1)

In [2]:
arr = np.arange(1,11).reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2.Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. (Score:1)

In [9]:
aru=np.arange(1,21)
arr=aru[5:15]
arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


3.How to compute the mean, median, and standard deviation of a numpy array?Use the array you created above (Score 1)

In [10]:
print(aru)
print("Mean=",np.mean(aru))
print("median=",np.median(aru))
print("Standard deviation=",np.std(aru))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Mean= 10.5
median= 10.5
Standard deviation= 5.766281297335398


4.Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [12]:
print(f"This is {x.ndim}D array")
x=np.array([[1,2,3,4],[5,6,7,8],[8,3,4,5]])
print(x)

print(f"This is {y.ndim}D array")
y = np.array([2,2,2,2])
print(y)
print("Result")
result= x - y
print(result)

NameError: name 'x' is not defined

5.Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. (Score: 2)

In [ ]:
df = pd.DataFrame({
    "name":["pranav","umer","adhil","shone","paraveen","said","jithin","daine","anju","aswathy"],
    "age" :[27,31,24,25,26,24,28,26,28,32],
    "gender":["M","M","M","M","M","M","M","F","F","F"]
})
print(df)

5.1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. (Score: 1)

In [ ]:
ddf=[' Programmer',' Manager', 'Analyst,']
df['occupation']=np.resize(ddf,len(df))
df

5.2) Select the rows of the dataframe where the age is greater than or equal to 30. (Score: 1)

In [ ]:
dft=df[df['age']>=30]
print(dft)

5.3) Convert this dataframe to a CSV file and read that CSV file, and finally display

In [ ]:
df.to_csv("all.csv",index=False)
df_read=pd.read_csv("all.csv")
print(df_read)


In [ ]:
df.reset_index()